name: Documentation
run-name: Building the documentation for the release

on:
    push:
        branches: release
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Building documentation
            - id: build
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
            - run: yarn
            - run: npx typedoc src/index.ts
    deploy:
        needs: build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploying documentation
            - id: deploy
            - uses: actions/deploy-pages@v2
