name: lint-code
run-name: Formatting the code and checking for linting errors

on:
    push:
        branches: dev

jobs:
    lint:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
            # Installing dependencies
            - run: npm install

            # Formatting the code
            - run: npm run format

            # Checking for linting errors
            - run: npm run lint

            # Commiting the code
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Formatted the code
                  branch: dev
